project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  sidebar:
    style: floating

metadata-files: [nbdev.yml]

publish:
  site:
    repository: "git@github.com:ajroberts0417/Fractal-LLM-Course.git"
    branch: gh-pages
